### PR TITLE
git clone was taking too long: [ImgBot] Lossless compression of images

### PR DESCRIPTION
**Pull request by davidgumberg**
*Total -- 20,515.17kb -> 19,494.91kb (4.97%)

/images/20110129085828!Noimage.png -- 5.87kb -> 1.89kb (67.83%)
/images/Noimage.png -- 5.87kb -> 1.89kb (67.83%)
/images/360Flash_logo.png -- 13.42kb -> 6.39kb (52.34%)
/images/Timing_attack_dgtool.PNG -- 15.85kb -> 7.61kb (51.99%)
/images/Nandpinout.png -- 20.26kb -> 12.14kb (40.07%)
/images/USB_SPI_Programmer.png -- 92.12kb -> 58.45kb (36.55%)
/images/20120303123615!URLHivTIQ.png -- 9.37kb -> 6.49kb (30.79%)
/images/Timing_attack_degraded.PNG -- 9.37kb -> 6.49kb (30.79%)
/images/360_rs232_build.png -- 268.69kb -> 195.99kb (27.06%)
/images/Quadrants.png -- 128.88kb -> 96.86kb (24.85%)
/images/Dump32_Finished_and_List.png -- 52.00kb -> 39.84kb (23.4%)
/images/256-512MB.png -- 25.29kb -> 19.50kb (22.87%)
/images/Timing_attack_degraded_settings.PNG -- 7.04kb -> 5.49kb (22.01%)
/images/HeaderLocations.png -- 366.05kb -> 322.26kb (11.96%)
/images/Quake-icon.png -- 32.92kb -> 29.01kb (11.87%)
/images/Satapinout3.jpg -- 96.02kb -> 85.04kb (11.43%)
/images/120px-10e7li8y8ros.2oewmy.22.png -- 21.56kb -> 19.44kb (9.84%)
/images/Vision.cam.jpg -- 55.57kb -> 50.25kb (9.57%)
/images/Samsung_HDD_Front.jpg -- 424.29kb -> 384.42kb (9.4%)
/images/120px-10ec5deoj0gw.vd9qbv.22.png -- 9.31kb -> 8.46kb (9.04%)
/images/Gentoo_fuses.jpg -- 69.69kb -> 63.66kb (8.66%)
/images/PongScreen.jpg -- 39.13kb -> 35.83kb (8.43%)
/images/Xbox_4532_Kernel.JPG -- 46.78kb -> 43.01kb (8.05%)
/images/Xell_fusesets.jpg -- 108.22kb -> 100.01kb (7.59%)
/images/Infectus_Write_NAND.PNG -- 73.46kb -> 68.39kb (6.9%)
/images/Infectus_Read_NAND.PNG -- 73.29kb -> 68.26kb (6.85%)
/images/H-Slim29.jpg -- 174.20kb -> 162.78kb (6.56%)
/images/Trinity_R4R1.jpg -- 274.63kb -> 256.93kb (6.44%)
/images/88W8786U-NAP2.JPG -- 55.60kb -> 52.08kb (6.34%)
/images/H-Slim11.jpg -- 42.23kb -> 39.59kb (6.25%)
/images/H-Slim37.jpg -- 275.77kb -> 258.62kb (6.22%)
/images/KL_Microsoft_XBOX_380_CPU_ES.jpg -- 261.56kb -> 245.34kb (6.2%)
/images/H-Slim36.jpg -- 325.36kb -> 305.41kb (6.13%)
/images/H-Slim13.jpg -- 38.10kb -> 35.80kb (6.02%)
/images/H-Slim34.jpg -- 290.42kb -> 273.35kb (5.88%)
/images/H-Slim35.jpg -- 307.81kb -> 290.00kb (5.79%)
/images/H-Slim12.jpg -- 46.23kb -> 43.59kb (5.71%)
/images/H-Slim33.jpg -- 199.99kb -> 188.89kb (5.55%)
/images/H-Slim27.jpg -- 114.96kb -> 108.67kb (5.47%)
/images/H-Slim31.jpg -- 124.59kb -> 117.83kb (5.42%)
/images/H-Slim25.jpg -- 81.26kb -> 76.93kb (5.34%)
/images/H-Slim32.jpg -- 148.34kb -> 140.43kb (5.33%)
/images/H-Slim18.jpg -- 87.50kb -> 82.93kb (5.21%)
/images/H-Slim41.jpg -- 945.28kb -> 896.04kb (5.21%)
/images/H-Slim10.jpg -- 63.88kb -> 60.67kb (5.02%)
/images/H-Slim7.jpg -- 53.12kb -> 50.46kb (5.02%)
/images/Media-remote.jpg -- 19.53kb -> 18.56kb (4.97%)
/images/H-Slim28.jpg -- 55.43kb -> 52.68kb (4.96%)
/images/H-Slim8.jpg -- 55.28kb -> 52.66kb (4.74%)
/images/H-Slim21.jpg -- 77.74kb -> 74.07kb (4.71%)
/images/H-Slim23.gif -- 21.06kb -> 20.07kb (4.67%)
/images/H-Slim43.jpg -- 734.29kb -> 700.70kb (4.57%)
/images/H-Slim6.jpg -- 61.33kb -> 58.57kb (4.5%)
/images/Therm_removed.jpg -- 244.27kb -> 233.36kb (4.47%)
/images/H-Slim20.jpg -- 148.57kb -> 141.96kb (4.45%)
/images/H-Slim19.jpg -- 49.88kb -> 47.67kb (4.43%)
/images/H-Slim40.jpg -- 277.55kb -> 265.28kb (4.42%)
/images/H-Slim45.jpg -- 386.07kb -> 369.31kb (4.34%)
/images/Reversejatg.jpg -- 694.25kb -> 664.39kb (4.3%)
/images/H-Slim38.jpg -- 308.15kb -> 294.91kb (4.3%)
/images/H-Slim1.jpg -- 333.77kb -> 319.55kb (4.26%)
/images/H-Slim9.jpg -- 87.81kb -> 84.10kb (4.23%)
/images/H-Slim14.jpg -- 129.67kb -> 124.29kb (4.15%)
/images/H-Slim42.jpg -- 593.25kb -> 568.68kb (4.14%)
/images/H-Slim22.jpg -- 59.34kb -> 56.89kb (4.13%)
/images/Conextant_video.jpg -- 15.94kb -> 15.29kb (4.09%)
/images/Xcalibur_video.jpg -- 14.05kb -> 13.48kb (4.05%)
/images/H-Slim5.jpg -- 67.67kb -> 64.95kb (4.02%)
/images/Avoid_FAT_Bottom.jpg -- 292.36kb -> 280.63kb (4.01%)
/images/H-Slim17.jpg -- 81.02kb -> 77.87kb (3.89%)
/images/H-Slim44.jpg -- 556.02kb -> 534.52kb (3.87%)
/images/Avoid_FAT_Top.jpg -- 282.28kb -> 271.50kb (3.82%)
/images/H-Slim2.jpg -- 293.83kb -> 282.89kb (3.72%)
/images/H-Slim39.jpg -- 241.00kb -> 232.11kb (3.69%)
/images/Mupen64plus.png -- 19.16kb -> 18.46kb (3.67%)
/images/Alt_point_Slim_Diagram.jpg -- 189.97kb -> 183.00kb (3.67%)
/images/16MB.png -- 40.11kb -> 38.64kb (3.66%)
/images/H-Slim16.jpg -- 76.39kb -> 73.64kb (3.6%)
/images/RGH_Slim_Diagram.jpg -- 304.52kb -> 293.65kb (3.57%)
/images/Uart_all.jpg -- 207.67kb -> 200.27kb (3.56%)
/images/H-Slim15.jpg -- 81.68kb -> 78.90kb (3.4%)
/images/H-Slim4.jpg -- 1,038.24kb -> 1,003.61kb (3.34%)
/images/Jasper1DONE12.jpg -- 104.77kb -> 101.31kb (3.3%)
/images/H-Slim26.jpg -- 258.15kb -> 250.20kb (3.08%)
/images/Eeprom.jpg -- 342.61kb -> 332.17kb (3.05%)
/images/Xenon1DONE12.jpg -- 96.66kb -> 93.73kb (3.03%)
/images/H-Slim24.jpg -- 363.83kb -> 352.92kb (3%)
/images/Alt_point_FAT_Diagram.jpg -- 738.99kb -> 717.26kb (2.94%)
/images/XBOX360_Fat_NandPro_LPCH2148_PIC18F2455_Diagram.jpg -- 258.38kb -> 250.79kb (2.94%)
/images/H-Slim3.jpg -- 403.23kb -> 391.47kb (2.92%)
/images/RGH_Fat_Diagram.jpg -- 722.52kb -> 702.07kb (2.83%)
/images/Flash.jpg -- 80.98kb -> 78.71kb (2.79%)
/images/H-Slim30.jpg -- 64.76kb -> 62.96kb (2.78%)
/images/Hd_outL.jpg -- 210.66kb -> 204.83kb (2.77%)
/images/Focus_video.jpg -- 27.03kb -> 26.44kb (2.19%)
/images/20100903163652!Xbox_360_revisions_xenon_motherboard.jpg -- 230.80kb -> 225.76kb (2.18%)
/images/Xbox_360_revisions_xenon_motherboard.jpg -- 230.80kb -> 225.76kb (2.18%)
/images/Hdd_unscrew.jpg -- 180.33kb -> 176.57kb (2.08%)
/images/Vchip-location.jpg -- 27.45kb -> 26.90kb (2%)
/images/Underside3.jpg -- 61.89kb -> 60.66kb (2%)
/images/Pcsxr.png -- 16.85kb -> 16.52kb (1.98%)
/images/Hd_open4.jpg -- 203.29kb -> 199.47kb (1.88%)
/images/ZFOJ_Jtag_free60.jpg -- 89.23kb -> 87.71kb (1.71%)
/images/NullDC_logo.png -- 33.90kb -> 33.51kb (1.15%)
/images/X360Pro_noeeprom.jpg -- 89.37kb -> 88.37kb (1.11%)
/images/Timing_attack_1888_boot_success.jpg -- 35.18kb -> 34.90kb (0.81%)
/images/XBOX360_Slim_NandPro_LPCH2148_PIC18F2455_Diagram.jpg -- 382.83kb -> 380.21kb (0.69%)
/images/2782Fig01.gif -- 5.79kb -> 5.76kb (0.62%)
/images/Face_removedzz.jpg -- 121.13kb -> 120.77kb (0.3%)
/images/J2B1_SCON.png -- 250.81kb -> 250.42kb (0.16%)
/images/Pong_yt.jpg -- 3.48kb -> 3.47kb (0.11%)
/images/H-Slim46.jpg -- 132.55kb -> 132.43kb (0.09%)
/images/20100413094309!Xbox360Logo.jpg -- 18.49kb -> 18.48kb (0.07%)
/images/Xbox360Logo.jpg -- 18.49kb -> 18.48kb (0.07%)
/images/R6t3zoom.png -- 584.10kb -> 583.83kb (0.05%)
/images/Smsplus_logo.jpeg -- 5.55kb -> 5.55kb (0.02%)

### CODE REVIEW

**Comment by apmorton** [comment]
This will actually make a clone take *longer*, since it's going to almost double the size of the repository.

A git clone has to download all commits since the beginning of time.

**Comment by davidgumberg** [comment]
sometimes you have to put 2 and 2 together

**Comment by davidgumberg** [comment]
hold the phone cowboy, Git doesn't have binary deltas????

**Comment by tuxuser** [comment]
What you would need to do it rebase the whole repo - not worth for the minimal gain.

**Pull request closed without merging**
