### PR TITLE
Nav and Redirect

### LINKED ISSUE #38: Redirects should be moved to MkDocs' built-in redirect system
See: https://pypi.org/project/mkdocs-redirects/

by @halotroop2288

### PR DESCRIPTION
**Pull request by halotroop2288**
I'm gonna fix #38, #39 and #40 in this PR.

I have done what I said I was gonna do:

- MkDocs navigation has been implemented
- Images and articles have moved to subfolders matching their category
- Redundant category *pages* have been deleted
- Redundant redirect *pages* have been deleted

This PR still needs some cleanup. Links may be broken. (but there are none reported by the compiler.)

## Before merge:
- [x] Fix merge conflict
- [ ] Move the rest of the pages to their folders
- [ ] Make sure every page has been added to the MkDocs nav
- [ ] Use `/**` absolute links instead of `../**` relative links
- [x] Remove redundant "Xbox-360-" from category folder names
      (This site is all about the 360! It's implied!)

## Merge
Please squash this PR.

## Post-merge:
- Index pages should be created for each category, like this:

  mkdocs.yml
  ```yml
  nav:
    - Category:
      - 'category/index.yml'
  ```
- [!TODO](https://free60.org/!TODO) and [!Pages That Need Updates](https://free60.org/!Pages_That_Need_Updates) should be deleted and posted as an issue here on GitHub.
- [Index](https://free60.org) should be rewritten. There's probably not a lot of need for most of the current content, but all of the links will be broken!

### CODE REVIEW

**Comment by halotroop2288** [comment]
@tuxuser If you would like to review, you can start viewing file changes now. I'm finishing up my changes. I need to find a way to fix all the dead links (they're not being warned by the compiler)

**Comment by halotroop2288** [comment]
RFC: Should "Category:" links at the bottom of every page that were added as a remnant of Mediawiki be kept?

Removing them instead of fixing them would save me a lot of work.

**Comment by halotroop2288** [comment]
As far as this PR goes, I think I've reached the limit of my usefulness. I don't know enough to categorize all of the remaining pages.

**Comment by tuxuser** [comment]
Pages needing updates:
- SFCX: Xbox Flash Controller, integrated into the Southbridge. Probabl, if there are any links to SFCX right now, they should rather point to https://github.com/Free60Project/wiki/blob/master/docs/NAND.md#flash-controllers
- XCP: Here's a good resource: https://gitlab.com/0x8081/libxcp

**Comment by halotroop2288** [comment]
Thanks, tuxuser! I'll put that to good use for my KSY files!

**Comment by halotroop2288** [comment]
I am not sure how much of these tasks I completed, but this could use a real review.

I'd like to add more onto this wiki, from findings while working on Xenia. Such as kernel min version 1861 which has yet to be found.
Snippet from Xenia log

**Pull request merged**
